/* ═══════════════════════════════════════════════════
   DIGITAL DENTAL ZONE — Blog Post Data (fallback)
   Mirrors supabase/schema.sql seed. Used when the
   Supabase backend is unreachable so blog pages still work.
   ═══════════════════════════════════════════════════ */

window.DDZ_BLOG_POSTS = [
  {
    slug: 'digital-dentistry-intraoral-scanners-barishal',
    language: 'en',
    title_en: 'What is Digital Dentistry? How Intraoral Scanners are Changing Dental Care in Barishal',
    title_bn: null,
    excerpt_en: 'Discover how intraoral scanners are replacing messy moulds with precise 3D digital impressions — and how Barishal\u2019s first female digital dentist is leading the change.',
    excerpt_bn: null,
    body_en: [
      '## What is Digital Dentistry?',
      'Digital dentistry simply means using modern computer technology in place of traditional manual methods during dental treatment. Instead of old-fashioned putty impressions, sticky moulds and guesswork, a dentist uses tools like **intraoral scanners**, **digital X-rays** and **CAD/CAM software** to diagnose and treat with far greater precision.',
      '## What is an Intraoral Scanner?',
      'An intraoral scanner is a small hand-held device with a camera that is passed gently over your teeth. In under a minute it creates a highly accurate **3D digital model** of your mouth — no gagging on mould paste, no discomfort.',
      '- **No messy impressions** — the 3D scan replaces the old putty moulds.',
      '- **Extreme precision** — the digital model is accurate to fractions of a millimetre.',
      '- **Instant results** — the scan appears on screen immediately, so you can see exactly what the dentist sees.',
      '## Why It Matters in Barishal',
      'Most dental clinics still use traditional methods. When crowns, veneers or implants are made the old way, a small inaccuracy in the mould can lead to a poor-fitting restoration. Digital scanning removes that guesswork entirely.',
      'Dr. Nusrat Naiem is the **first female doctor to use an intraoral scanner in Barishal Division** — and only the second user in the whole of Bangladesh. For her patients, this means:',
      '- Faster and more comfortable appointments',
      '- Crowns and veneers that fit better and last longer',
      '- Implant planning that is far more predictable',
      '- A fully digital smile design you can preview before treatment',
      '## Who Can Benefit?',
      'Almost everyone! Whether you need a simple filling, a crown, veneers for a smile makeover, or a full dental implant, digital scanning makes the process smoother. Even children find the scanner easy and fun — there is no scary moulding tray.',
      '## Want to Experience Digital Dentistry?',
      'Call or WhatsApp **01674-878470** to book a consultation at Digital Dental Zone, 15 Parara Road, Barishal. See for yourself how comfortable modern dental care can be.'
    ].join('\n'),
    body_bn: null,
    tags: ['digital dentistry', 'intraoral scanner', 'barishal'],
    author: 'Dr. Nusrat Naiem',
    published: '2026-06-14',
    cover: null
  },
  {
    slug: 'root-canal-vs-extraction',
    language: 'en',
    title_en: 'Root Canal vs. Extraction: When to Save Your Tooth',
    title_bn: null,
    excerpt_en: 'A root canal can save a badly decayed tooth that extraction would remove forever. Here\u2019s how to decide — and what each treatment costs in Barishal.',
    excerpt_bn: null,
    body_en: [
      '## The First Question: Can the Tooth Be Saved?',
      'When a tooth is badly decayed or infected, many patients immediately assume it must come out. But in most cases a **root canal treatment (RCT)** can save the natural tooth — and keeping your own tooth is almost always the better long-term choice.',
      '## What is a Root Canal?',
      'Deep inside every tooth is a chamber containing the nerve and blood supply — the pulp. When decay reaches the pulp, it becomes infected, causing severe pain. Root canal treatment removes the infected pulp, cleans and disinfects the canals, then seals the tooth. The tooth remains in place, crowned and fully functional.',
      'At Digital Dental Zone, RCT is performed **using an Endomotor** — a modern electric instrument that makes the procedure faster, more accurate and virtually painless. RCT starts at **৳8,000**, with a full package (RCT + post core + zirconia crown) available at **৳25,000**.',
      '## When Extraction Is Necessary',
      'Extraction is the right choice when:',
      '- The tooth is too badly destroyed to restore',
      '- The infection is severe and the root can no longer be saved',
      '- There is advanced gum (periodontal) disease that has loosened the tooth',
      '- It is a wisdom tooth causing repeated problems',
      'Simple adult extraction costs **৳3,000** per tooth; surgical or semi-surgical extraction ranges from **৳4,000 to ৳15,000** depending on the case.',
      '## Why Saving the Tooth Matters',
      '- **Better chewing function** — natural teeth withstand force better than replacements.',
      '- **Prevents bone loss** — your jawbone stays stimulated and healthy.',
      '- **Cheaper long-term** — replacing a lost tooth with an implant or bridge costs far more than one root canal.',
      '- **No drifting** — neighbouring teeth do not shift into the gap.',
      '## The Bottom Line',
      'If your tooth is in pain, do not wait until it is beyond saving. The sooner you see a dentist, the more options you have. Dr. Nusrat will always try to save your natural tooth first — and only recommend extraction when it truly is the best option.',
      'Call **01674-878470** to book an appointment at Digital Dental Zone, Barishal.'
    ].join('\n'),
    body_bn: null,
    tags: ['root canal', 'extraction', 'rct', 'barishal'],
    author: 'Dr. Nusrat Naiem',
    published: '2026-07-03',
    cover: null
  },
  {
    slug: 'dental-implants-barishal-cost-procedure',
    language: 'en',
    title_en: 'Dental Implants in Barishal: Cost, Procedure, and What to Expect',
    title_bn: null,
    excerpt_en: 'Everything you need to know about dental implants in Barishal — the cost, the step-by-step procedure, and what the recovery really feels like.',
    excerpt_bn: null,
    body_en: [
      '## What is a Dental Implant?',
      'A dental implant is a small titanium screw that is placed into the jawbone to replace the root of a missing tooth. On top of it, a natural-looking crown is attached. The result looks, feels and functions like a real tooth.',
      '## Why Choose an Implant?',
      '- **Looks completely natural** — indistinguishable from your own teeth',
      '- **Prevents bone loss** — the implant keeps your jawbone healthy',
      '- **No damage to other teeth** — unlike bridges, neighbouring teeth stay untouched',
      '- **Eat and speak with confidence** — the implant is as strong as a natural root',
      '- **Long-lasting** — with good care, implants can last decades',
      '## The Procedure — Step by Step',
      '1. **Consultation & digital planning** — Dr. Nusrat examines you, takes X-rays, and plans the implant position digitally. You receive a clear cost estimate before anything starts.',
      '2. **Implant placement** — a minor surgical procedure performed under local anaesthesia. The implant is gently placed into the bone.',
      '3. **Healing (2–4 months)** — the implant fuses with your bone in a process called osseointegration.',
      '4. **Crown placement** — once healed, a custom crown is fixed onto the implant, completing your new tooth.',
      '## What About Pain?',
      'The placement itself is done under anaesthesia, so you feel no pain during the procedure. Afterward, most patients manage with simple painkillers and return to normal activities within a day or two.',
      '## How Much Does an Implant Cost in Barishal?',
      'A dental implant at Digital Dental Zone starts from **৳1,20,000** (negotiable). The final figure depends on your individual case — for example, whether you need a bone graft or sinus lift first. You will always receive a transparent, itemised estimate at your consultation.',
      '## Am I a Candidate?',
      'Most adults with one or more missing teeth are good candidates. You should have healthy gums and enough bone to support the implant. If bone has receded, grafting options exist. During your free initial consultation Dr. Nusrat will assess your suitability honestly.',
      '## Book Your Implant Consultation',
      'Call or WhatsApp **01674-878470** to book your appointment at Digital Dental Zone — 15 Parara Road, Barishal. As the **first female implant surgeon in Barishal**, Dr. Nusrat brings postgraduate precision to every implant case.'
    ].join('\n'),
    body_bn: null,
    tags: ['dental implant', 'implant barishal', 'cost'],
    author: 'Dr. Nusrat Naiem',
    published: '2026-07-17',
    cover: null
  },
  {
    slug: 'digital-dentistry-intraoral-scanners-barishal-bn',
    language: 'bn',
    title_en: null,
    title_bn: 'ডিজিটাল ডেন্টিস্ট্রি কী? বরিশালে ইন্ট্রাওরাল স্ক্যানার যেভাবে দাঁতের চিকিৎসায় স্বস্তি এনে দিচ্ছে',
    excerpt_en: null,
    excerpt_bn: 'আঠালো ছাঁচের অস্বস্তি ছাড়াই মাত্র ১ মিনিটে ৩ডি ডিজিটাল স্ক্যানের মাধ্যমে নিখুঁত দাঁতের চিকিৎসা নিন। জানুন বরিশালের প্রথম নারী ডিজিটাল ডেন্টিস্টের অভিজ্ঞতা।',
    body_en: null,
    body_bn: [
      '## ডিজিটাল ডেন্টিস্ট্রি কী এবং এটি কেন গুরুত্বপূর্ণ?',
      'ডিজিটাল ডেন্টিস্ট্রি হলো দাঁতের চিকিৎসায় সনাতন বা কষ্টদায়ক পদ্ধতির বদলে আধুনিক কম্পিউটার ও ৩ডি প্রযুক্তির নির্ভরযোগ্য ব্যবহার। মুখে আঠালো পেস্টের ছাঁচ দেওয়া বা অনুমানের ওপর নির্ভর না করে এখন **৩ডি ইন্ট্রাওরাল স্ক্যানার**, **ডিজিটাল এক্স-রে** এবং **ক্যাড/ক্যাম (CAD/CAM)** সফটওয়্যারের মাধ্যমে প্রতিটি দাঁতের সূক্ষ্মতম গঠন স্ক্রিনে দেখে নির্ভুল চিকিৎসা করা সম্ভব হচ্ছে।',
      '## ইন্ট্রাওরাল স্ক্যানার কীভাবে কাজ করে?',
      'ইন্ট্রাওরাল স্ক্যানার অত্যন্ত ছোট ও মসৃণ একটি হ্যান্ডহেল্ড ডিভাইস। দাঁতের ওপর আলতোভাবে ঘুরিয়ে মাত্র ৬০ সেকেন্ডের মধ্যে এটি মুখের একটি স্পষ্ট ও নিখুঁত **ত্রিমাত্রিক (3D) কালার মডেল** তৈরি করে।',
      '- **কোনো আঠালো পেস্টের অস্বস্তি নেই:** পুরনো পদ্ধতিতে মুখে আঠালো ছাঁচ নেওয়ার যে বমি বমি ভাব বা কষ্ট হতো, তা এখন অতীত।',
      '- **মাইক্রন লেভেলের নিখুঁত পরিমাপ:** ডিজিটাল মডেলটি মিলিমিটারের ক্ষুদ্রতম ভগ্নাংশ পর্যন্ত নিখুঁত মাপ দেয়।',
      '- **তাৎক্ষণিক স্ক্রিন প্রিভিউ:** স্ক্যান করার সাথে সাথে রোগী নিজেও মনিটরে নিজের দাঁতের অবস্থা পরিষ্কারভাবে দেখতে পারেন।',
      '## বরিশালবাসীর জন্য এটি কেন বিশেষ অর্জন?',
      'আমাদের দেশে বেশিরভাগ ডেন্টাল ক্লিনিকে এখনও সনাতন পদ্ধতিতে ক্রাউন, ক্যাপ বা ইমপ্ল্যান্টের মাপ নেওয়া হয়। সামান্য ভুলের কারণে ক্যাপ ঠিকমতো না বসে মাড়িতে ব্যথা বা ফাঁকা থেকে যেতে পারে। ডিজিটাল স্ক্যানিং সেই ভুল পুরোপুরি দূর করে।',
      'ডাঃ নুসরাত নাঈম **বরিশাল বিভাগে ইন্ট্রাওরাল স্ক্যানার ব্যবহারকারী প্রথম নারী চিকিৎসক** এবং সমগ্র বাংলাদেশে মাত্র দ্বিতীয় সার্জন যিনি এই প্রযুক্তি নিজ চেম্বারে সার্বক্ষণিক ব্যবহার করছেন। এর ফলে রোগীরা পাচ্ছেন:',
      '- দ্রুততম ও অত্যন্ত আরামদায়ক চিকিৎসা সেশন',
      '- নিখুঁতভাবে বসে এমন টেকসই জিরকোনিয়া ক্রাউন ও ভিনিয়ার',
      '- ইমপ্ল্যান্টের জন্য ১০০% নিশ্চিত ও পূর্ব-পরিকল্পিত গাইডেন্স',
      '- চিকিৎসার আগেই নিজের কাঙ্ক্ষিত হাসির ডিজিটাল সিমুলেশন দেখার সুযোগ',
      '## কারা এই ডিজিটাল সেবা নিতে পারবেন?',
      'সাধারণ দাঁতের ফিলিং, ক্যাপ বসানো, ফাঁকা দাঁত সোজা করা, স্মাইল মেকওভার কিংবা সম্পূর্ণ স্থায়ী ডেন্টাল ইমপ্ল্যান্ট — যেকোনো চিকিৎসার জন্যই ৩ডি স্ক্যানার অত্যন্ত উপযোগী। ছোট শিশুরাও কোনো ভয় না পেয়ে হাসিমুখে এই স্ক্যান করিয়ে নেয়।',
      '## আধুনিক ডিজিটাল চিকিৎসার অভিজ্ঞতা নিন',
      'আপনার দাঁতের যেকোনো পরামর্শ বা অ্যাপয়েন্টমেন্টের জন্য সরাসরি কল বা হোয়াটসঅ্যাপ করুন **01674-878470** নম্বরে। ঠিকানা: ডিজিটাল ডেন্টাল জোন, ১৫ পরারা রোড (সুরভী বুকিং অফিসের বিপরীতে), বরিশাল শহর।'
    ].join('\n'),
    tags: ['ডিজিটাল ডেন্টিস্ট্রি', 'ইন্ট্রাওরাল স্ক্যানার', 'বরিশাল'],
    author: 'ডাঃ নুসরাত নাঈম',
    published: '2026-06-15',
    cover: null
  },
  {
    slug: 'root-canal-vs-extraction-bn',
    language: 'bn',
    title_en: null,
    title_bn: 'দাঁত তোলা নাকি রুট ক্যানাল? কোন সিদ্ধান্তটি আপনার জন্য সেরা',
    excerpt_en: null,
    excerpt_bn: 'তীব্র দাঁতের ব্যথায় দাঁত ফেলে না দিয়ে রুট ক্যানালের মাধ্যমে নিজের প্রাকৃতিক দাঁত সারাজীবনের জন্য রক্ষা করা সম্ভব। জেনে নিন বিশেষজ্ঞ পরামর্শ ও খরচ।',
    body_en: null,
    body_bn: [
      '## প্রথম বিবেচনা: প্রাকৃতিক দাঁতটি কি রক্ষা করা সম্ভব?',
      'দাঁতে তীব্র ক্যাভিটি বা ইনফেকশন হলে অনেকেই আতঙ্কে দাঁত ফেলে দেওয়ার সিদ্ধান্ত নেন। কিন্তু আধুনিক চিকিৎসাবিজ্ঞানে প্রাকৃতিক দাঁত সংরক্ষণ করাই প্রথম লক্ষ্য। বেশিরভাগ ক্ষেত্রে একটি সঠিক **রুট ক্যানাল ট্রিটমেন্ট (RCT)** দাঁতটিকে দীর্ঘস্থায়ীভাবে রক্ষা করতে পারে।',
      '## রুট ক্যানাল চিকিৎসা কীভাবে কাজ করে?',
      'প্রতিটি দাঁতের গভীরে সংবেদনশীল নার্ভ ও রক্তনালী (পাল্প) থাকে। ক্যাভিটি গভীর হয়ে পাল্পে পৌঁছালে তীব্র যন্ত্রণা শুরু হয়। রুট ক্যানাল পদ্ধতিতে আধুনিক যন্ত্র দিয়ে ভেতরের সংক্রমিত অংশ সম্পূর্ণ পরিষ্কার ও জীবাণুমুক্ত করে সিল করে দেওয়া হয়। এরপর একটি মজবুত ক্রাউন বা ক্যাপ পরিয়ে দাঁতটিকে আগের মতোই খাবার চিবানোর উপযোগী করে তোলা হয়।',
      'ডিজিটাল ডেন্টাল জোনে অত্যাধুনিক **রোটারি এন্ডোমোটর ও এপেক্স লোকেটার** দিয়ে সম্পূর্ণ ব্যথামুক্তভাবে রুট ক্যানাল করা হয়। এখানে আরসিটি শুরু হয় **৳৮,০০০** থেকে এবং ফুল প্যাকেজ (আরসিটি + পোস্ট কোর + জিরকোনিয়া ক্রাউন) পাওয়া যায় **৳২৫,০০০**-এ।',
      '## কখন দাঁত তোলা ছাড়া উপায় থাকে না?',
      'শুধুমাত্র নিম্নলিখিত জটিল পরিস্থিতিতে অভিজ্ঞ ডাক্তার দাঁত তোলার পরামর্শ দেন:',
      '- দাঁতের গঠন এতটাই ভেঙে গেছে যা কোনোভাবেই ক্যাপ পরানোর উপযোগী নয়',
      '- শেকড়ে মারাত্মক ইনফেকশন যা হাড়ের গভীরে ছড়িয়ে পড়েছে',
      '- মাড়ির মারাত্মক রোগের কারণে দাঁত সম্পূর্ণ নড়বড়ে হয়ে গেলে',
      '- বাঁকা হয়ে ওঠা সমস্যাযুক্ত আক্কেল দাঁত যা পাশের দাঁত ক্ষতিগ্রস্ত করছে',
      'ডিজিটাল ডেন্টাল জোনে সাধারণ দাঁত তোলার খরচ **৳৩,০০০** এবং সার্জিক্যাল এক্সট্রাকশন **৳৪,০০০ থেকে ৳১৫,০০০** (কেসের জটিলতার ওপর নির্ভর করে)।',
      '## কেন প্রাকৃতিক দাঁত বাঁচানোই সবচেয়ে বুদ্ধিমানের কাজ?',
      '- **খাবার চিবানোর স্বাভাবিক আনন্দ:** আসল দাঁত যে চাপ সহ্য করতে পারে, কৃত্রিম বিকল্পে তা সবসময় মেলে না।',
      '- **চোয়ালের হাড়ের সুরক্ষা:** দাঁত থাকলে চোয়ালের হাড় ক্ষয়ে মুখের আকৃতি বদলে যায় না।',
      '- **দীর্ঘমেয়াদে সর্বোচ্চ সাশ্রয়:** একটি দাঁত ফেলে দিয়ে সেখানে নতুন ব্রিজ বা ইমপ্ল্যান্ট করার চেয়ে রুট ক্যানাল করা অনেক বেশি সাশ্রয়ী।',
      '- **দাঁতের সৌন্দর্য বজায় রাখা:** পাশের দাঁতগুলো ফাঁকা জায়গায় হেলে পড়ে না।',
      '## চিকিৎসকের পরামর্শ',
      'দাঁতে হালকা শিরশিরানি বা ব্যথা হলেই দ্রুত ডাক্তার দেখান। যত দ্রুত চিকিৎসা শুরু করবেন, দাঁত বাঁচানো তত সহজ হবে। ডাঃ নুসরাত সবসময় আগে আপনার প্রাকৃতিক দাঁতটি রক্ষা করার সর্বোচ্চ চেষ্টা করেন।',
      'পরামর্শ ও সিরিয়ালের জন্য সরাসরি কল করুন **01674-878470** নম্বরে — ডিজিটাল ডেন্টাল জোন, বরিশাল।'
    ].join('\n'),
    tags: ['রুট ক্যানাল', 'দাঁত তোলা', 'আরসিটি', 'বরিশাল'],
    author: 'ডাঃ নুসরাত নাঈম',
    published: '2026-07-04',
    cover: null
  },
  {
    slug: 'dental-implants-barishal-cost-procedure-bn',
    language: 'bn',
    title_en: null,
    title_bn: 'বরিশালে ডেন্টাল ইমপ্ল্যান্ট: খরচ, চিকিৎসা পদ্ধতি ও প্রয়োজনীয় তথ্য',
    excerpt_en: null,
    excerpt_bn: 'হারানো দাঁতের স্থায়ী সমাধান ডেন্টাল ইমপ্ল্যান্ট। টাইটানিয়াম রুট ও জিরকোনিয়া ক্রাউনের মাধ্যমে প্রাকৃতিক দাঁতের মতো খাবার চিবানোর পূর্ণ তৃপ্তি ফিরে পান।',
    body_en: null,
    body_bn: [
      '## ডেন্টাল ইমপ্ল্যান্ট কী?',
      'ডেন্টাল ইমপ্ল্যান্ট হলো হারানো দাঁতের সবচেয়ে আধুনিক ও দীর্ঘস্থায়ী বৈজ্ঞানিক সমাধান। এটি বায়োকম্প্যাটিবল মেডিকেল-গ্রেড টাইটানিয়াম স্ক্রু যা চোয়ালের হাড়ে প্রাকৃতিক শেকড়ের মতো স্থাপন করা হয় এবং তার ওপর একটি আসল দাঁতের মতোই সুন্দর জিরকোনিয়া ক্রাউন বসানো হয়।',
      '## কেন ডেন্টাল ইমপ্ল্যান্ট সবচেয়ে সেরা বিকল্প?',
      '- **১০০% প্রাকৃতিক অনুভূতি:** দেখতে এবং খাবার চিবানোর শক্তিতে একদম আসল দাঁতের মতো।',
      '- **চোয়ালের হাড় ক্ষয়রোধ:** হাড়কে সক্রিয় রেখে মুখের স্বাভাবিক সৌন্দর্য ও বয়সের ছাপ রক্ষা করে।',
      '- **পাশের ভালো দাঁতের কোনো ক্ষতি হয় না:** ব্রিজের মতো পাশের অক্ষত দাঁত কাটতে বা ঘষতে হয় না।',
      '- **সারাজীবনের নির্ভরযোগ্যতা:** সঠিক যত্ন ও পরিষ্কার-পরিচ্ছন্নতায় ইমপ্ল্যান্ট সারাজীবন সুস্থ থাকে।',
      '## চিকিৎসা প্রক্রিয়া — ধাপসমূহ:',
      '1. **পরামর্শ ও ৩ডি ডিজিটাল প্ল্যানিং:** ডাঃ নুসরাত ৩ডি স্ক্যানার ও এক্স-রের মাধ্যমে চোয়ালের হাড়ের গভীরতা পরিমাপ করে চিকিৎসার সঠিক নকশা ও স্বচ্ছ খরচের বিবরণ দেন।',
      '2. **ইমপ্ল্যান্ট স্থাপন:** লোকাল অ্যানেস্থেসিয়ার মাধ্যমে ছোট ও সম্পূর্ণ ব্যথামুক্ত প্রক্রিয়ায় টাইটানিয়াম স্ক্রুটি হাড়ে স্থাপন করা হয়।',
      '3. **হাড়ের সাথে সংযুক্তি (২–৩ মাস):** অসিওইন্টিগ্রেশন প্রক্রিয়ায় স্ক্রুটি হাড়ের সাথে প্রাকৃতিক শেকড়ের মতো শক্ত হয়ে জোড়া লাগে।',
      '4. **স্থায়ী ক্রাউন সংযোজন:** কাস্টম-মেড জিরকোনিয়া ক্রাউন সংযুক্ত করে চিকিৎসা সম্পন্ন করা হয়।',
      '## চিকিৎসায় কি ব্যথা লাগে?',
      'অ্যানেস্থেসিয়ার কারণে ইমপ্ল্যান্ট বসানোর সময় রোগী কোনো ব্যথা অনুভব করেন না। পরবর্তীতে সাধারণ ওষুধেই রোগীরা দ্রুত সুস্থ বোধ করেন এবং পরের দিন থেকেই স্বাভাবিক কাজকর্মে ফিরতে পারেন।',
      '## বরিশালে ইমপ্ল্যান্টের আনুমানিক খরচ কত?',
      'ডিজিটাল ডেন্টাল জোনে সিঙ্গেল টুথ ডেন্টাল ইমপ্ল্যান্ট **৳১,২০,০০০** থেকে শুরু (আলোচনাসাপেক্ষ)। কেসের ওপর নির্ভর করে হাড়ের ঘনত্ব কম থাকলে বোন গ্রাফটিং লাগতে পারে। প্রথম সাক্ষাতেই আপনাকে সম্পূর্ণ স্বচ্ছ আইটেম-ভিত্তিক ব্যয়ের তালিকা দেওয়া হবে।',
      '## কারা ইমপ্ল্যান্ট করাতে পারবেন?',
      'যেকোনো প্রাপ্তবয়স্ক সুস্থ ব্যক্তি যাদের এক বা একাধিক দাঁত হারিয়ে গেছে, তারা ইমপ্ল্যান্ট নিতে পারেন। প্রাথমিক পরামর্শে ডাঃ নুসরাত আপনার মাড়ি ও হাড় পরীক্ষা করে সঠিক দিকনির্দেশনা দেবেন।',
      '## বিশেষজ্ঞ পরামর্শ নিন',
      '**বরিশালের প্রথম নারী ইমপ্ল্যান্ট সার্জন** হিসেবে ডাঃ নুসরাত নাঈম প্রতিটি কেসে স্নাতকোত্তর পর্যায়ের নিখুঁত যত্ন নিশ্চিত করেন। বিস্তারিত জানতে ও সিরিয়ালের জন্য যোগাযোগ করুন: **01674-878470** — ডিজিটাল ডেন্টাল জোন, ১৫ পরারা রোড, বরিশাল।'
    ].join('\n'),
    tags: ['ডেন্টাল ইমপ্ল্যান্ট', 'বরিশাল ইমপ্ল্যান্ট', 'চিকিৎসা ব্যয়'],
    author: 'ডাঃ নুসরাত নাঈম',
    published: '2026-07-18',
    cover: null
  }
];